---
#Apache Tasks

# Install HTTPD
- name: "Install apache"
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: "Run httpd"
  service:
    name: apache2
    state: started
    enabled: yes

- name: "change /var/www/html permissions"
  file:
    path: /var/www/html
    state: directory
    mode: 0777

- name: "install index page"
  copy:
      src: index.html
      dest: /var/www/html/index.html
      backup: yes