---
- hosts: all
  become: true
  remote_user: ubuntu

  pre_tasks:
    - name: update
      apt:
          update_cache: true

    - name: install pip
      apt:
        name: python3-pip
        state: latest

    - name: install boto3 and botocore
      apt:
        name:
        - python3-boto3
        - python3-botocore

  roles:
    - prepare
    - apache