version: 2.1

defaults: &awscli_docker_container
  docker:
    - image: amazon/aws-cli

commands:
  run_cloudformation_template_cli:
    steps:
    - run: 
        command: |
          aws cloudformation deploy --template-file aws_cfn_template.yml --stack-name udacityProject --region=us-west-1
jobs:
# ***** AWS INFRASTRUCTURE *****
  run_cloudformation_template_job:
    <<: *awscli_docker_container
    
    steps:
      - checkout
      - run_cloudformation_template_cli
      - run:
          name: Run when the job is complete
          command: |
            echo "AWS Infrastructure Deployed"
      - run:
          name: Adding EC2 Instance Name to Inventory
          command: |
            aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress'
# ***** AWS INFRASTRUCTURE END *****

# ***** SOFTWARE DEPLOYMENT START *****
  deploy_software:
    docker:
      - image: python:3.9.0-alpine3.12
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["3f:64:99:a3:57:c6:de:85:0b:9b:57:47:4f:19:c4:e9"]
      - run: # These commands are running inside the container
          name: Install Dependencies
          command: |
            apt install ansible
      - run:
          name: Configure Server
          command: |
            ansible-playbook -vvvv -i inventory/aws_ec2.yml playbook.yml

# ***** SOFTWARE DEPLOYMENT END *****
workflows:
  run_cloudformation_template_workflow:
    jobs:
      - run_cloudformation_template_job
      - deploy_software:
          requires:
            - run_cloudformation_template_job